version: '3.7'
volumes:
    database:
services:
    db:
        image: mysql:latest
        container_name: talk-mysql
        ports:
            - 3307:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=orion-talk-service
            - MYSQL_DATABASE=orion-talk-service
            - MYSQL_USER=orion-talk-service
            - MYSQL_PASSWORD=orion-talk-service
    phpMyAdmin:
            image: phpmyadmin/phpmyadmin:latest
            container_name: talk-phpmyadmin
            environment:
                - PMA_ARBITRARY=1
            links:
                - db
            ports:
                - 8081:80
            volumes:
                - /sessions
    jaeger:
        image: jaegertracing/all-in-one:1.17
        container_name: talk-jaeger
        ports:
             - 5775:5775
             - 6831:6831
             - 6832:6832
             - 5778:5778 
             - 16686:16686 
             - 14268:14268 
             - 14250:14250
             - 9411:9411
    service:
        # image: rodrigoprestesmachado/orion-talk-image:version-0.1
        build: .
        container_name: talk-service
        ports:
            - 9081:9080
            - 9444:9443