version: '3.7'
volumes:
    database:
services:
    db:
        image: mysql:latest
        container_name: talk-mysql
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=orion-talk-service
            - MYSQL_DATABASE=orion-talk-service
            - MYSQL_USER=orion-talk-service
            - MYSQL_PASSWORD=orion-talk-service
    phpMyAdmin:
            image: phpmyadmin/phpmyadmin:latest
            container_name: talk-phpmyadmin
            environment:
                - PMA_ARBITRARY=1
            links:
                - db
            ports:
                - 8081:80
            volumes:
                - /sessions
    service:
        # image: rodrigoprestesmachado/orion-talk-image:version-0.1
        build: .
        depends_on:
            - "db"
            - "phpMyAdmin"
        container_name: talk-service
        ports:
            - 9080:9080
            - 9443:9443